from rest_framework.authtoken.views import obtain_auth_token
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookViewSet, BookList

# Step 1: Create a router
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Optional: keep the old ListAPIView
    path('books/', BookList.as_view(), name='book-list'),

    # Include all CRUD routes generated by the router
    path('', include(router.urls)),
    
    path('api/get-token/', obtain_auth_token, name='api-token')
]
